#ifndef _CB_SOLAR_CONFIG_HPP
#define _CB_SOLAR_CONFIG_HPP

#define DEBUG 1
#define GRAVITY 9.8
#define DT 0.01
#define FRAME_RATE_LIMIT 120U
#define VELOCITY_DECAY_FACTOR 0.0
#define MAX_BODIES 32U
#define INITIAL_ASTEROID_MASS 20000

#endif
